// Test-only stand-in for Ponder's virtual "ponder:schema" module. The real
// module is generated by Ponder's runtime from ponder.schema.ts; under
// plain vitest we just re-export the real table definitions directly, since
// tests only need the table objects as opaque keys (see the mocked
// context.db in the handler tests), not the runtime-registered version.
export * from "../../ponder.schema.js";
